import pathlib
f = pathlib.Path('docs/Client_QA_500_Tieng_Viet.md')

# Write Q121-200 in compact format
qa_list = [
    ("Q121", "AI co the xu ly cac truong hop y te phuc tap khong?", "Co, dac biet la lane phuc tap (Sonnet 4.5 / Qwen3.5-Plus): bieu hien da he thong, trieu chung mo ho, xem xet dieu kien hiem gap, suy luan xac suat voi trich dan. Hieu suat: ~92% do chinh xac tren cac truong hop phuc tap (PoC). Tu choi khi khong chac chan. Cung cap chan doan phan biet duoc xep hang theo xac suat voi bang chung ho tro."),
    ("Q122", "Lam the nao de AI xu ly cac truong hop nhi khoa khac nhau?", "Chuyen mon hoa nhi khoa: lieu luong dua tren can nang bat buoc, cham soc phu hop theo tuoi, cac can nhac phat trien, cac huong dan cu the cho nhi khoa (AAP, v.v.), kiem tra chong chi dinh nghiem ngat hon, cac can nhac giao tiep voi cha me. Vi du phan hoi cho 'ibuprofen cho tre 5 tuoi': yeu cau can nang, tinh toan lieu luong dua tren can nang, kiem tra gioi han tuoi, chong chi dinh, theo doi cu the cho nhi khoa."),
    ("Q123", "AI co the goi y cac dieu tri thay the khong?", "Co, voi minh bach day du: Hang dau: khuyen nghi tieu chuan. Thay the cho: chong chi dinh, di ung, chi phi, tuy chon. Liet ke voi muc do bang chung. Thao luan ve danh doi. Lam noi bat cac yeu to quyet dinh. Dinh dang: 'Chinh: [thuoc A] - [bang chung]. Thay the neu [dieu kien]: [thuoc B] - [bang chung]. Khuyen nghi phu thuoc vao cac yeu to benh nhan X, Y, Z.'"),
    ("Q124", "Dieu gi xay ra khi benh nhan co nhieu nhu cau chuyen khoa?", "Phoi hop da chuyen khoa: AI kich hoat nhieu agent, cac can nhac xuyen chuyen khoa, tuong tac thuoc tren cac he thong, ke hoach cham soc phoi hop, phan hoi tich hop duy nhat. Vi du: benh nhan tieu duong voi CKD va CHF -> Noi tiet: quan ly tieu duong. Than hoc: dieu tri dieu chinh CKD. Tim mach: cac can nhac suy tim. Ket hop: khuyen nghi tich hop ton trong ca ba."),
    ("Q125", "AI co the giup voi cac cuoc trao doi dong thuan thong tin khong?", "Co, vai tro ho tro: giai thich thu thuat/dieu tri bang ngon ngu don gian, liet ke cac rui ro vat chat, thao luan ve cac lua chon thay the, phac thao loi ich, cung cap tai lieu giao duc benh nhan. Luu y: bac si van co trach nhiem chinh trong quy trinh dong thuan. AI chuan bi nhung khong thay the. Chu ky cua benh nhan van thuoc ve bac si."),
    ("Q126", "Lam the nao de AI xu ly cham soc cuoi doi?", "Chuyen khoa nhan cam: chuyen mon cham soc giam nhe, cac cuoc trao doi muc tieu cham soc, quan ly trieu chung, cac cuoc trao doi voi gia dinh, cac can nhac van hoa, nhan cam ton giao. AI cung cap: cac lua chon giam nhe dua tren bang chung, cac khung giao tiep, nhan cam van hoa-ton giao, thong tin gioi thieu hospice. Quan trong: phan xet cua bac si va su dong cam cua con nguoi la thiet yeu. AI ho tro, khong thay the."),
    ("Q127", "AI xu ly cac cau hoi suc khoe tam than nhu the nao?", "Cau hinh co the: Tieu chuan: dinh tuyen den cac agent tam than/tam ly. Bao thu: gioi thieu tu van chuyen khoa. Giao duc: cung cap thong tin, gioi thieu de cham soc. Huong dan cu the: Nhan biet y dinh tu tu: leo thang ro rang den chuyen khoa. Trieu chung nghiem trong: gioi thieu ngay lap tuc. Cac cau hoi thuong xuyen: huong dan AI + chuyen khoa khi can. Bao mat: bao ve quyen rieng tu bo sung. Cau hinh benh vien: muc do tich cuc AI trong phan hoi suc khoe tam than. Hau het: bao thu."),
    ("Q128", "AI co the goi y cham soc phong ngua cho benh nhan khong?", "Co, phong ngua dua tren bang chung: sang loc dua tren tuoi, khuyen nghi dua tren rui ro, huong dan tiem chung, tu van loi song, sang loc ung thu. Tich hop voi EHR: trang thai phong ngua cua benh nhan, ngay sang loc cuoi cung, cac khoang trong duoc xac dinh. Giup bac si uu tien va thao luan ve cham soc phong ngua."),
    ("Q129", "Lam the nao de AI cap nhat voi cac thuoc moi?", "Nhieu co che: co so du lieu phe duyet HSA duoc dong bo, cap nhat danh muc thuoc WHO, giam sat tai lieu duoc pham, thay doi danh muc thuoc benh vien, ket qua thu nghiem noi bo. Tan suat: phe duyet moi trong vong 2-4 tuan, huong dan chinh trong vong 1 tuan, giao thuc noi bo theo thoi gian thuc, su dung ngoai nhan trong duoc giam sat can than. Han che: thuoc rat moi (vai thang) co the co du lieu han che; AI ghi nhan dieu nay."),
    ("Q130", "AI co the du doan ket qua benh nhan khong?", "Kha nang du doan han che trong pham vi hien tai: phan tang rui ro co the, mo hinh ket qua: tinh nang tuong lai, du bao ca nhan hoa: them tiem nang. Hien tai: AI giup danh gia trang thai hien tai, lua chon dieu tri. Khong thay the cac mo hinh du doan chuyen biet (nhu APACHE, CHA2DS2, v.v.). Co the duoc them nhu dich vu bo sung."),
]

content = f.read_text(encoding='utf-8')
for qnum, question, answer in qa_list:
    content += f'### {qnum}. {question}\n\n**A.** {answer}\n\n---\n\n'
f.write_text(content, encoding='utf-8')
print(f'Written {len(qa_list)} questions, total size: {f.stat().st_size}')
