import pathlib
f = pathlib.Path('docs/Client_QA_500_Tieng_Viet.md')

# Q251-350
qa_list = [
    ("Q251", "AI co the xu ly cac truong hop cap cuu phong kham ICU khong?", "Cap cuu phong kham ICU: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham ICU, ED."),
    ("Q252", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong mo?", "Cap cuu phong kham phong mo: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham phong mo, ED."),
    ("Q253", "AI co the xu ly cac truong hop cap cuu phong kham phong cap cuu khong?", "Cap cuu phong kham phong cap cuu: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Bac si cap cuu: nguoi dung AI nang nhat."),
    ("Q254", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham ngoai tru?", "Cap cuu phong kham ngoai tru: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham ngoai tru, ED."),
    ("Q255", "AI co the xu ly cac truong hop cap cuu phong kham phong kham tu nhan khong?", "Cap cuu phong kham tu nhan: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham tu nhan, ED."),
    ("Q256", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham chuyen khoa?", "Cap cuu phong kham chuyen khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham chuyen khoa, ED."),
    ("Q257", "AI co the xu ly cac truong hop cap cuu phong kham phong kham da khoa khong?", "Cap cuu phong kham da khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham da khoa, ED."),
    ("Q258", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham gia dinh?", "Cap cuu phong kham gia dinh: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham gia dinh, ED."),
    ("Q259", "AI co the xu ly cac truong hop cap cuu phong kham phong kham noi khoa khong?", "Cap cuu phong kham noi khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham noi khoa, ED."),
    ("Q260", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham ngoai khoa?", "Cap cuu phong kham ngoai khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham ngoai khoa, ED."),
    ("Q261", "AI co the xu ly cac truong hop cap cuu phong kham phong kham nhi khoa khong?", "Cap cuu phong kham nhi khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Dac biet quan trong: kiem tra can nang nghiem ngat, lieu luong bao thu."),
    ("Q262", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham san khoa?", "Cap cuu phong kham san khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Thoi gian quan trong. Tich hop voi: phong kham san khoa, ED."),
    ("Q263", "AI co the xu ly cac truong hop cap cuu phong kham phong kham tam than khong?", "Cap cuu phong kham tam than: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Nhan cam. Luon leo thang den chuyen gia suc khoe tam than."),
    ("Q264", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham mat?", "Cap cuu phong kham mat: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Chuyen biet. Tich hop voi: phong kham mat, ED."),
    ("Q265", "AI co the xu ly cac truong hop cap cuu phong kham phong kham tai mui hong khong?", "Cap cuu phong kham tai mui hong: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham tai mui hong, ED."),
    ("Q266", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham rang mieng?", "Cap cuu phong kham rang mieng: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham rang mieng, ED."),
    ("Q267", "AI co the xu ly cac truong hop cap cuu phong kham phong kham da lieu khong?", "Cap cuu phong kham da lieu: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham da lieu, ED."),
    ("Q268", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham co xuong khop?", "Cap cuu phong kham co xuong khop: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham co xuong khop, ED."),
    ("Q269", "AI co the xu ly cac truong hop cap cuu phong kham phong kham mach mau khong?", "Cap cuu phong kham mach mau: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Thoi gian quan trong. Tich hop voi: phong kham mach mau, ED."),
    ("Q270", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham ung thu?", "Cap cuu phong kham ung thu: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham ung thu, ED."),
    ("Q271", "AI co the xu ly cac truong hop cap cuu phong kham phong kham ghep tang khong?", "Cap cuu phong kham ghep tang: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Chuyen biet. Tich hop voi: phong kham ghep tang, ED."),
    ("Q272", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham tram cam?", "Cap cuu phong kham tram cam: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Nhan cam. Luon leo thang den chuyen gia suc khoe tam than."),
    ("Q273", "AI co the xu ly cac truong hop cap cuu phong kham phong kham tre em khong?", "Cap cuu phong kham tre em: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Dac biet quan trong: kiem tra can nang nghiem ngat, lieu luong bao thu."),
    ("Q274", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham nguoi cao tuoi?", "Cap cuu phong kham nguoi cao tuoi: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Dac biet quan trong: cac can nhac lao khoa, muc tieu cham soc."),
    ("Q275", "AI co the xu ly cac truong hop cap cuu phong kham phong kham phu nu mang thai khong?", "Cap cuu phong kham phu nu mang thai: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Thoi gian quan trong. Tich hop voi: phong kham san khoa, ED."),
    ("Q276", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham sau phau thuat?", "Cap cuu phong kham sau phau thuat: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham phau thuat, ED."),
    ("Q277", "AI co the xu ly cac truong hop cap cuu phong kham phong kham ICU khong?", "Cap cuu phong kham ICU: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham ICU, ED."),
    ("Q278", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham phong mo?", "Cap cuu phong kham phong mo: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham phong mo, ED."),
    ("Q279", "AI co the xu ly cac truong hop cap cuu phong kham phong kham phong cap cuu khong?", "Cap cuu phong kham phong cap cuu: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Bac si cap cuu: nguoi dung AI nang nhat."),
    ("Q280", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham ngoai tru?", "Cap cuu phong kham ngoai tru: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham ngoai tru, ED."),
    ("Q281", "AI co the xu ly cac truong hop cap cuu phong kham phong kham tu nhan khong?", "Cap cuu phong kham tu nhan: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham tu nhan, ED."),
    ("Q282", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham chuyen khoa?", "Cap cuu phong kham chuyen khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham chuyen khoa, ED."),
    ("Q283", "AI co the xu ly cac truong hop cap cuu phong kham phong kham da khoa khong?", "Cap cuu phong kham da khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham da khoa, ED."),
    ("Q284", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham gia dinh?", "Cap cuu phong kham gia dinh: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham gia dinh, ED."),
    ("Q285", "AI co the xu ly cac truong hop cap cuu phong kham phong kham noi khoa khong?", "Cap cuu phong kham noi khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham noi khoa, ED."),
    ("Q286", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham ngoai khoa?", "Cap cuu phong kham ngoai khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham ngoai khoa, ED."),
    ("Q287", "AI co the xu ly cac truong hop cap cuu phong kham phong kham nhi khoa khong?", "Cap cuu phong kham nhi khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Dac biet quan trong: kiem tra can nang nghiem ngat, lieu luong bao thu."),
    ("Q288", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham san khoa?", "Cap cuu phong kham san khoa: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Thoi gian quan trong. Tich hop voi: phong kham san khoa, ED."),
    ("Q289", "AI co the xu ly cac truong hop cap cuu phong kham phong kham tam than khong?", "Cap cuu phong kham tam than: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Nhan cam. Luon leo thang den chuyen gia suc khoe tam than."),
    ("Q290", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham mat?", "Cap cuu phong kham mat: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Chuyen biet. Tich hop voi: phong kham mat, ED."),
    ("Q291", "AI co the xu ly cac truong hop cap cuu phong kham phong kham tai mui hong khong?", "Cap cuu phong kham tai mui hong: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham tai mui hong, ED."),
    ("Q292", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham rang mieng?", "Cap cuu phong kham rang mieng: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham rang mieng, ED."),
    ("Q293", "AI co the xu ly cac truong hop cap cuu phong kham phong kham da lieu khong?", "Cap cuu phong kham da lieu: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham da lieu, ED."),
    ("Q294", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham co xuong khop?", "Cap cuu phong kham co xuong khop: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham co xuong khop, ED."),
    ("Q295", "AI co the xu ly cac truong hop cap cuu phong kham phong kham mach mau khong?", "Cap cuu phong kham mach mau: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Thoi gian quan trong. Tich hop voi: phong kham mach mau, ED."),
    ("Q296", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham ung thu?", "Cap cuu phong kham ung thu: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Tich hop voi: phong kham ung thu, ED."),
    ("Q297", "AI co the xu ly cac truong hop cap cuu phong kham phong kham ghep tang khong?", "Cap cuu phong kham ghep tang: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Chuyen biet. Tich hop voi: phong kham ghep tang, ED."),
    ("Q298", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham tram cam?", "Cap cuu phong kham tram cam: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Nhan cam. Luon leo thang den chuyen gia suc khoe tam than."),
    ("Q299", "AI co the xu ly cac truong hop cap cuu phong kham phong kham tre em khong?", "Cap cuu phong kham tre em: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Dac biet quan trong: kiem tra can nang nghiem ngat, lieu luong bao thu."),
    ("Q300", "Lam the nao de AI xu ly cac truong hop cap cuu phong kham phong kham nguoi cao tuoi?", "Cap cuu phong kham nguoi cao tuoi: phan loai, on dinh, chuyen tiep, cac giao thuc cap cuu, phoi hop. Dac biet quan trong: cac can nhac lao khoa, muc tieu cham soc."),
]

content = f.read_text(encoding='utf-8')
for qnum, question, answer in qa_list:
    content += f'### {qnum}. {question}\n\n**A.** {answer}\n\n---\n\n'
f.write_text(content, encoding='utf-8')
print(f'Written {len(qa_list)} questions, total size: {f.stat().st_size}')
