import pathlib
f = pathlib.Path('docs/Client_QA_500_Tieng_Viet.md')

qa_list = [
    ("Q131", "EHR cu hon hoac khong tieu chuan co the tich hop khong?", "Co, nhieu con duong: HL7 v2 (tieu chuan cu, hau het EHR cu ho tro, 30-80k USD), tich hop co so du lieu (truc tiep doc co so du lieu EHR, 50-150k USD), API tuy chinh (xay dung bo chuyen doi, 80-200k USD), su dung doc lap (bac si nhap context thu cong, khong co chi phi bo sung). Khuyen nghi: danh gia EHR truoc hop dong; bao gia tich hop rieng biet."),
    ("Q132", "Chung toi co can di chuyen bat ky du lieu hien co vao he thong khong?", "Tuy chon nhung co gia tri. Bat buoc: PDF bao cao thu nghiem noi bo, giao thuc cu the cua benh vien, tai lieu tham khao theo khoa. Quy trinh: kiem ke du lieu, an danh hoa, tai len, lập chi muc (24-48 gio), xac thuc. Quy mo: benh vien nho 50-100 tai lieu (1 tuan), benh vien vua 200-500 (2 tuan), benh vien lon 1000-3000 (4-6 tuan). Chi phi: nho 5-10k USD, vua 15-25k USD, lon 30-60k USD."),
    ("Q133", "Chung toi co the them cac khoa hoac chuyen khoa hon sau nay khong?", "Co, duoc thiet ke de mo rong. Them khoa moi: Giai doan 1 Quyet dinh (2 tuan), Giai doan 2 Cau hinh (1 tuan), Giai doan 3 Nhap noi dung (1-3 tuan), Giai doan 4 Kiem tra (1 tuan), Giai doan 5 Ra mat (1 ngay). Tong: 5-8 tuan moi khoa moi. Chi phi moi khoa: ky thuat 10-20k USD, noi dung lam sang 5-15k USD, kiem tra thi diem 5-10k USD. Tong: 20-45k USD moi chuyen khoa moi."),
    ("Q134", "Tong dau tu ban dau cho mot benh vien la bao nhieu?", "Tong chi phi Nam 1 (benh vien dien hinh): Giay phep phan mem (hang nam) 40-80k USD, Dich vu trien khai 50-150k USD, Thoi gian nhan vien benh vien 40-60k USD, Tich hop EHR 20-50k USD, Thiet lap tuan thu 20-40k USD, Dao tao & quan ly thay doi 15-30k USD. Tong Nam 1: 185-410k USD. Nam 2+ hang nam: 70-135k USD. TCO 5 nam: 465-960k USD. So sanh voi gia tri: 7-15 trieu USD tiet kiem trong 5 nam. ROI: 8-20x."),
    ("Q135", "Cau truc hop dong dien hinh la gi?", "Cac loai hop dong: MSA (Thoa thuan Dich vu Chu), SLA (Thoa thuan Cap do Dich vu), DPA (Thoa thuan Xu ly Du lieu, tuan thu PDPA), SOW (Pham vi Cong viec, cu the theo du an). Dieu khoan tieu chuan: Thoi han ban dau 36 thang, Tu dong gia han 12 thang voi tang toi da 5%, Thong bao ket thuc 90 ngay, Tra lai du lieu 30 ngay, Gioi han trach nhiem 12 thang phi, Boi thuong tuong ho. Cac mo hinh dinh gia: phi hang thang phat (pho bien nhat), theo ghe bac si, theo truy van, lai."),
    ("Q136", "Thoi han hop dong toi thieu la bao lau va cac dieu khoan ket thuc la gi?", "Thoi han toi thieu: 36 thang (3 nam). Tai sao 3 nam: thu hoi chi phi trien khai, on dinh cho ca hai ben, tieu chuan nganh cho SaaS y te. Cac thoi han ngan hon (ngoai le): 24 thang: phi bao hiem 10%, 12 thang: phi bao hiem 25%, Thi diem/PoC: 3-6 thang voi gia khong tieu chuan. Cac kich ban ket thuc: Ket thuc thoi han (thong bao 90 ngay, chuyen doi muot), Ket thuc vi tien loi (phi ket thuc som: gia tri hop dong con lai duoc phan bo), Ket thuc vi vi pham (vi pham vat chat, thoi gian khac phuc 30 ngay, khong co phi ket thuc som), Bat kha khang (khong co phat)."),
    ("Q137", "Ai tu phia chung toi can tham gia vao viec trien khai?", "Ban do cac ben lien quan: Nha tai tro dieu hanh (CEO/COO/CFO/CMO), Lanh dao du an (CMIO, Quan ly Du an, Giam doc Lam sang), Chuyen gia lam sang (1-2 moi khoa), Nhom CNTT (Giam doc CNTT, Ky su truong, Ky su Bao mat, Ky su Mang), Tuan thu (Can bo Tuan thu, DPO, Co van Phap ly). Cam ket thoi gian: Nha tai tro dieu hanh 1 gio/tuan, CMIO 5 gio/tuan, Chuyen gia lam sang 5-10 gio/tuan, Truong CNTT 10-15 gio/tuan, Tuan thu 5 gio/tuan. Tong no luc benh vien: ~200 gio trong 10 tuan."),
    ("Q138", "Dieu gi xay ra neu chung toi muon thay doi nha cung cap trong khi trien khai?", "Thay doi giua chung trien khai la hiem nhung co the. Ly do: thay doi kinh doanh dang ke, phat hien lua chon thay the tot hon, that bai trong viec cung cap, thay doi quy dinh. Chi phi chuyen doi giua chung trien khai: Chi phi nha cung cap goc: 50-100k USD mat, Chi phi nha cung cap moi: 100-200k USD khoi dau moi, Thoi gian nhan vien benh vien: 50-100k USD, Tong chi phi chuyen doi: 200-400k USD. Khuyen nghi: Danh gia nha cung cap ky luong truoc khi ky hop dong. Thi diem voi 2 nha cung cap truoc khi ky hop dong. Tieu chi thanh cong ro rang tu ngay 1."),
    ("Q139", "He thong co the tuy chinh theo nhu cau cu the cua benh vien khong?", "Co, nhieu cap do: Cap 1 Cau hinh (khong co code, bao gom, 1-2 tuan), Cap 2 Prompt tuy chinh (it code, 5-10k USD, 2-3 tuan), Cap 3 Quy trinh lam viec tuy chinh (it code, 15-30k USD, 4-6 tuan), Cap 4 Tich hop tuy chinh (code, 40-100k USD, 8-12 tuan), Cap 5 Tinh nang tuy chinh (code dang ke, 100-300k USD, 6-9 thang). Cac tuy chinh pho bien: cau hinh chuyen khoa, boi canh dia phuong, tich hop quy trinh lam viec, bao cao tuy chinh. Khuyen nghi: Nam 1 tuy chinh toi thieu, Nam 2 xac dinh khoang trong, Nam 3+ dua tren nhu cau duoc chung minh."),
    ("Q140", "Lam the nao de xu ly bien dong nhan su trong khi trien khai?", "Bien dong nhan su benh vien: Nha tai tro du an roi: ghi lai tat ca quyet dinh, nhieu ben lien quan, tai lieu tieu chuan, xac dinh nguoi thay the. Truong CNTT thay doi: chuyen giao kien thuc, tai lieu trong wiki benh vien, ho tro ky thuat cua Nova, tac dong toi thieu. Can bo tuan thu thay doi: tai lieu tuan thu toan dien, DPIA va kiem toan bao mat co san, con mat moi co the co loi. Bien dong nhan su Nova: Giam doc Tai khoan roi: ke hoach chuyen tiep, CSM bao phu, nguoi thay the duoc phan cong, tac dong nho. Ky su truong xoay vong: nhieu ky su quen thuoc, tai lieu code, chia se kien thuc noi bo, tac dong nho."),
]

content = f.read_text(encoding='utf-8')
for qnum, question, answer in qa_list:
    content += f'### {qnum}. {question}\n\n**A.** {answer}\n\n---\n\n'
f.write_text(content, encoding='utf-8')
print(f'Written {len(qa_list)} questions, total size: {f.stat().st_size}')
